### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by freewil** [hellodigit/mocha-pipelines#1]
## Enhancements
- [x] Make default behavior to parallelize tests across available CPUs
- [x] README: Show all options (just output of `-h` ?)
- [x] README: explain how files are automatically split across pipelines/processes
- [x] README: explain goal of project (easy-on parallelization for existing mocha project with large number of tests)
